apiVersion: v1
kind: Pod
metadata:
  name: pinger
  namespace: default
  labels:
    name: pod
spec:
  restartPolicy: Never
  containers:
  - name: pinger
    image: 192.168.99.128:5000/pinger
    imagePullPolicy: Always