apiVersion: experiments.chaosplatform.com/v1alpha1
kind: Misconfiguration
metadata:
  name: misconfiguration-sample
spec:
  completions: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: bash-job
              image: bash:latest
              volumeMounts:
                  - mountPath: "/config/10-kubeadm.conf"
                    name: config-mount
              command: ["chmod", "645", "/config/10-kubeadm.conf"]
          restartPolicy: Never 
          volumes:
              - name: config-mount
                hostPath:
                    path: "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
                    type: File
