apiVersion: experiments.chaosplatform.com/v1alpha1
kind: Misconfiguration
metadata:
  name: kubelet-debug-mode
spec:
  kubeletMisconfigurations:
  podTemplate:
    restartPolicy: Never
    containers:
    - name: kubelet-misconfiguration
      image: 192.168.99.126:5000/kubelet-job:0.0.1
      imagePullPolicy: IfNotPresent
      lifecycle:
        preStop:
          exec:
            command: ["bash", "/home/kubelet-recovery.sh"]
      resources:
        limits:
          cpu: "0.2"
          memory: "100Mi"
