jobTemplate:
  spec:
    template:
      spec:
        hostPID: true
        containers:
          - name: bash-job
            image: bash:latest
            volumeMounts:
                - mountPath: "/config/10-kubeadm.conf"
                  name: config-mount
            command: ["chmod", "645", "/config/10-kubeadm.conf"]
        restartPolicy: Never 
        volumes:
            - name: config-mount
              hostPath:
                  path: "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
                  type: File