apiVersion: v1
kind: Pod
metadata:
  name: apiserver-misconfiguration
  namespace: default
spec:
  nodeName: "minikube"
  restartPolicy: Never
  hostPID: true
  containers:
  - name: apiserver-misconfiguration
    image: 192.168.99.135:5000/apiserver-misconfiguration
    args: ["1.2.7"]
    imagePullPolicy: Always
    volumeMounts:
    - name: etc-kubernetes
      mountPath: /etc/kubernetes
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/ready
    lifecycle:
      preStop:
        exec:
          command: ["python3", "/src/recovery.py"]
    resources:
      limits:
        cpu: "0.2"
        memory: "100Mi"
  volumes:
    - name: etc-kubernetes
      hostPath:
        path: "/etc/kubernetes"