apiVersion: experiments.chaosplatform.com/v1alpha1
kind: Pentesting
metadata:
  name: pwnable-hostpath
spec:
  podTemplate:
    restartPolicy: Never
    containers:
    - name: coredns-poison
      image: 192.168.99.135:5000/coredns-misconfig
      command: ["python3", "/src/main.py"]
      args: ["74.6.231.20", "google.com"]
      imagePullPolicy: Always
      readinessProbe:
        exec:
          command:
          - cat
          - /tmp/ready
      lifecycle:
        preStop:
          exec:
            command: ["python3", "/src/recovery.py"]
      resources:
        limits:
          cpu: "0.2"
          memory: "100Mi"
