apiVersion: v1
kind: Pod
metadata:
  name: dns-spoofer
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: dns-spoofer
    image: 192.168.99.134:5000/dns-spoofer
    imagePullPolicy: Always
    command:
      - "sleep"
      - "1000000"
    resources:
      limits:
        cpu: "0.2"
        memory: "100Mi"