apiVersion: v1
kind: Pod
metadata:
  name: kubelet-misconfiguration
  namespace: default
spec:
  restartPolicy: Never
  nodeName: worker-2
  containers:
  - name: kubelet-misconfiguration
    image: nilement/kubelet-job
    command: ["python3", "/src/main.py"]
    args: ["anonymous-auth", "disable-authorization"]
    imagePullPolicy: Always
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/ready
    lifecycle:
      preStop:
        exec:
          command: ["python3", "/src/recovery.py"]
    resources:
      limits:
        cpu: "0.2"
        memory: "100Mi"