apiVersion: v1
kind: Pod
metadata:
  name: cis-master
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: cis-master
    image: 192.168.99.126:5000/cis-worker:0.0.14
    args: ["4.1.1", "4.1.2", "4.1.5", "4.1.5", "4.1.6", "4.1.9", "4.1.10"]
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command: ["/src/main", "-r"]
    volumeMounts:
    - mountPath: "/config/10-kubeadm.conf"
      name: kubelet-service
    - mountPath: "/config/kubelet.conf"
      name: kubelet-kubeconf
    - mountPath: "/config/config.yaml"
      name: kubelet-conf
    resources:
      limits:
        cpu: "0.2"
        memory: "100Mi"
  volumes:
      - name: kube-apiserver
        hostPath:
            path: "/etc/kubernetes/manifests/kube-apiserver.yaml"
            type: File
      - name: kube-controller-manager
        hostPath:
            path: "/etc/kubernetes/manifests/kube-controller-manager.yaml"
            type: File
      - name: kube-scheduler
        hostPath:
            path: "/etc/kubernetes/manifests/kube-scheduler.yaml"
            type: File
      - name: etcd
        hostPath:
            path: "/etc/kubernetes/manifests/etcd.yaml"
            type: File
