apiVersion: v1
kind: Pod
metadata:
  name: coredns-poison
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: coredns-poison
    image: nilement/coredns-misconfig
    command: ["python3", "/src/main.py"]
    args: ["74.6.231.20", "google.com"]
    imagePullPolicy: Always
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/ready
    lifecycle:
      preStop:
        exec:
          command: ["python3", "/src/recovery.py"]
    resources:
      limits:
        cpu: "0.2"
        memory: "100Mi"