apiVersion: experiments.chaosplatform.com/v1alpha1
kind: DoS
metadata:
  name: dos-sample
spec:
  count: 0
  podSpec: 
      containers:
      - image: 192.168.99.124:5000/dostainer
        command: ["/app/fill-memory.sh", "5"]
        name: dos
        resources:
         limits:
           memory: "200Mi"
         requests:
           memory: "100Mi"
