apiVersion: v1
kind: Pod
metadata:
  name: custom-miner
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: custom-miner
    image: nilement/custom-miner
    imagePullPolicy: Always
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/ready