apiVersion: batch/v1
kind: Job
metadata:
  name: kubelet-recovery-job
spec:
  template:
    metadata:
      labels:
        app: kubelet-recovery-job
    spec:
      containers:
        - name: kubelet-recovery-job
          image: 192.168.99.126:5000/kubelet-job:latest
          command: ["bash", "/home/kubelet-recovery.sh"]
      restartPolicy: Never 