apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-injector-configmap
  namespace: default
data:
  sidecarconfig.yaml: |
    containers:
    - name: reader
      image: 192.168.99.131:5000/secret-reader
      imagePullPolicy: Always
      env:
        - name: LOGGER_PORT
          value: "8082"