apiVersion: v1
kind: Pod
metadata:
  name: scapy-victim
  namespace: default
spec:
  containers:
  - name: scapy
    image: ehlers/scapy
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
