apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: config-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["nodes/proxy"]
  verbs: ["get"]
