# permissions for end users to view arpdns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: arpdns-viewer-role
rules:
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - arpdns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - arpdns/status
  verbs:
  - get
