# permissions for end users to edit arpdns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: arpdns-editor-role
rules:
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - arpdns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - arpdns/status
  verbs:
  - get
