# permissions for end users to view behaviours.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: behaviour-viewer-role
rules:
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - behaviours
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - behaviours/status
  verbs:
  - get
