# permissions for end users to edit chaosapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaosapi-editor-role
rules:
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - chaosapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - chaosapis/status
  verbs:
  - get
