# permissions for end users to view cisexperiments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cisexperiment-viewer-role
rules:
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - cisexperiments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - cisexperiments/status
  verbs:
  - get
