# permissions for end users to edit cisexperiments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cisexperiment-editor-role
rules:
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - cisexperiments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - cisexperiments/status
  verbs:
  - get
