# permissions for end users to view cispersistents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cispersistent-viewer-role
rules:
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - cispersistents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - cispersistents/status
  verbs:
  - get
