# permissions for end users to edit cispersistents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cispersistent-editor-role
rules:
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - cispersistents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - cispersistents/status
  verbs:
  - get
