# permissions for end users to edit dos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dos-editor-role
rules:
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - dos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - dos/status
  verbs:
  - get
