# permissions for end users to edit misconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: misconfiguration-editor-role
rules:
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - misconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - misconfigurations/status
  verbs:
  - get
