# permissions for end users to edit pentestings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pentesting-editor-role
rules:
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - pentestings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - pentestings/status
  verbs:
  - get
