
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - chaosapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - chaosapis/finalizers
  verbs:
  - update
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - chaosapis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - cisexperiments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - cisexperiments/finalizers
  verbs:
  - update
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - cisexperiments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - cispersistents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - cispersistents/finalizers
  verbs:
  - update
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - cispersistents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - dos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - dos/finalizers
  verbs:
  - update
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - dos/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - misconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - misconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - misconfigurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - validations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - validations/finalizers
  verbs:
  - update
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - validations/status
  verbs:
  - get
  - patch
  - update
