# permissions for end users to edit validations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: validation-editor-role
rules:
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - validations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - experiments.chaosplatform.com
  resources:
  - validations/status
  verbs:
  - get
