apiVersion: v1
kind: ServiceAccount
metadata:
  name: powerful-pod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: powerful-pod-creator
subjects:
- kind: ServiceAccount
  name: powerful-pod
  namespace: default
roleRef:
  kind: Role
  name: pod-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-creator
rules:
- apiGroups: [""]
  resources: ["pods", "pod"]
  verbs: ["get", "create", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
